name: RFC Validation Pipeline
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - name: Remove unused files for further actions
      run: rm -fr .vscode && rm -fr latex

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22

    - name: Enable Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@908b263ff629f4cc17666315b7fd3ec127c6244d # v14

    - name: Check RFCs .md structure
      run: bash scripts/structure-check.sh

#    - name: Check Formatting
#      run: nix develop --command just format-check

#    - name: Check Spelling
#      run: nix develop --command just spell-check-ci
